classdef OmeTiffAPI<uint8
	enumeration
		OpenRead(0)
		OpenRW(1)
		Create(2)
		PixelType(3)
		DimensionOrder(4)
		SizeP(5)
		SizeX(6)
		SizeY(7)
		SizeI(8)
		SizeC(9)
		SizeZ(10)
		SizeT(11)
		ChannelColors(12)
		FileName(13)
		ImageDescription(14)
		ModifyParameters(15)
		ReadPixels(16)
		ReadPixelsI(17)
		WritePixels(18)
		WritePixelsI(19)
		PixelPointer(20)
		PixelPointerI(21)
		ReadToPointer(22)
		ReadToPointerI(23)
		WriteFromPointer(24)
		WriteFromPointerI(25)
		Close(26)
	end
	methods
		function varargout=Call(obj,varargin)
			varargout=cell(1,nargout);
			[Status,varargout{:}]=OmeBigTiff5D(uint8(obj),varargin{:});
			StatusCheck(Status);
		end
	end
end