#pragma once
#include <Mex工具.h>
//OirReader
API声明(Oir_CreateReader);
API声明(Oir_DeleteReader);
API声明(Oir_SizeX);
API声明(Oir_SizeY);
API声明(Oir_SizeC);
API声明(Oir_SizeZ);
API声明(Oir_SizeT);
API声明(Oir_SeriesInterval);
API声明(Oir_DeviceColors);
API声明(Oir_ReadPixels);
API声明(Oir_ReadToPointer);

//OmeTiffRWer
API声明(Tiff_OpenRead);
API声明(Tiff_OpenRW);
API声明(Tiff_OpenCreate);
API声明(Tiff_PixelType);
API声明(Tiff_DimensionOrder);
API声明(Tiff_SizeP);
API声明(Tiff_SizeX);
API声明(Tiff_SizeY);
API声明(Tiff_SizeI);
API声明(Tiff_SizeC);
API声明(Tiff_SizeZ);
API声明(Tiff_SizeT);
API声明(Tiff_ChannelColors);
API声明(Tiff_FileName);
API声明(Tiff_ImageDescription);
API声明(Tiff_ModifyParameters);
API声明(Tiff_ReadPixels);
API声明(Tiff_ReadPixelsI);
API声明(Tiff_WritePixels);
API声明(Tiff_WritePixelsI);
API声明(Tiff_PixelPointer);
API声明(Tiff_PixelPointerI);
API声明(Tiff_ReadToPointer);
API声明(Tiff_ReadToPointerI);
API声明(Tiff_WriteFromPointer);
API声明(Tiff_WriteFromPointerI);
API声明(Tiff_Close);